version: '3'

services:
  master:
    volumes:
      - ./build/locust/resources/${FOOBAR_REPO_PATH}:/mnt/locust
  
  worker:
    volumes:
      - ./build/locust/resources/${FOOBAR_REPO_PATH}:/mnt/locust

  mock-server:
    volumes:
      - ./build/mockserver/resources:/config 