version: '3'

services:
  master:
    image: locust-test/mqlocust
    ports:
     - "${MASTER_HOST_PORT}:${MASTER_CONTAINER_PORT}"
    command: -f /mnt/locust/locustfile.py --master -H http://master:${MASTER_CONTAINER_PORT}
  
  worker:
    image: locust-test/mqlocust
    command: -f /mnt/locust/locustfile.py --worker --master-host master