version: '3'

services:
  master:
    image: locust-test/mqlocust
    ports:
     - "${MASTER_HOST_PORT}:${MASTER_CONTAINER_PORT}"
    command: -f /mnt/locust/locustfile.py --master -H http://master:${MASTER_CONTAINER_PORT}
  
  worker:
    image: locust-test/mqlocust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  mock-server:
    image: mock-test/mqmock
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
